name: Smoke tests (DOM)

on:
    push:
        branches: [dev, master]
    pull_request:
        branches: [dev, master]

jobs:
    smoke:
        runs-on: ubuntu-latest
        services:
            mongodb:
                image: mongo:6.0
                ports:
                    - 27017:27017
                options: >-
                    --health-cmd "mongosh --eval 'db.adminCommand({ ping: 1 })'" 
                    --health-interval=5s --health-timeout=2s --health-retries=10
        env:
            PORT: 3003
            BASE_URL: http://127.0.0.1:3003
            MONGODB_URI: mongodb://127.0.0.1:27017/etsy_inventory_test

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Use Node.js 18.x
              uses: actions/setup-node@v4
              with:
                  node-version: '18'

            - name: Install dependencies
              run: |
                  npm ci

            - name: Seed deterministic test DB
              run: |
                  # Load deterministic test DB into the test database
                  npm run seed:test-db

            - name: Upload test DB receipt
              if: always()
              uses: actions/upload-artifact@v4
              with:
                  name: test-db-receipt
                  path: tmp/test-db-load-receipt.json

            - name: Start server (background)
              run: |
                  # start the app in the background and capture logs
                  nohup npm start > server.log 2>&1 &

            - name: Wait for server to be ready
              run: |
                  # wait up to 30s for the server to respond on HTTP
                  npx wait-on "http://127.0.0.1:3003" -t 30000

            - name: Run DOM smoke test
              env:
                  BASE_URL: http://127.0.0.1:3003
              run: |
                  # Try Playwright-based test, fall back to jsdom-based test
                  set -o pipefail
                  npm run smoke:dom

            - name: Upload server log (always)
              if: always()
              uses: actions/upload-artifact@v4
              with:
                  name: server-log
                  path: server.log
